services:
  api:
    build:
      context: ./api
    container_name: sgqui_api
    restart: unless-stopped
    ports:
      - "${API_PORT}:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_WAITFORCONN=${DB_WAITFORCONN}
      - DB_CONNLIMIT=${DB_CONNLIMIT}
      - DB_QUEUELIMIT=${DB_QUEUELIMIT}
      - DB_CONNTIMEOUT=${DB_CONNTIMEOUT}
    depends_on:
      - db
    command: ["npm", "start"]

  web:
    build:
      context: ./web
    container_name: sgqui_web
    restart: unless-stopped
    ports:
      - "${WEB_PORT}:8080"
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL}
    depends_on:
      - api
    command: ["npm", "start"]

  db:
    image: mysql:8.0
    container_name: sgqui_mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
    - "3306:3306"

volumes:
  db_data:
    name: sgqui_db_data